version: "3"
services:
  node-app:
    build: .
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DEV_DB_NAME=DGU
      - CLIENT_URL_DEV=http://localhost:3000
      - DEV_DB_PASSWORD=nevergiveupk21
      - NODE_ENV=production
      - DEV_APP_PORT=5005
      - VDOCYPHER_API_KEY=cJcruHf9Y2GoxPobF6ur48uKB63WgrYYVbP1inWl0r4gt9kGCto6DvzYfKYV1cHm




