version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:

